import type { Metadata } from 'next';
import './globals.css';
import ThemeRegistry from './lib/config/ThemeRegistry';

export const metadata: Metadata = {
  authors: [{ name: 'Daryll Moya' }],
  description: 'Generated by create next app',
  title: 'Puppy Adoption App',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <ThemeRegistry>
          <div className="min-h-screen flex flex-col">
            <header className="bg-blue-500 p-4 text-white text-center">
              <h1 className="text-2xl font-bold">Puppy Adoption Center</h1>
              <p className="text-sm">Find your perfect furry friend</p>
            </header>
            <main className="flex-1">
              <div className="container mx-auto px-4 py-8">{children}</div>
            </main>
            <footer className="bg-gray-300 p-4 text-center">
              <p>
                © {new Date().getFullYear()} Puppy Adoption Center. All rights
                reserved.
              </p>
            </footer>
          </div>
        </ThemeRegistry>
      </body>
    </html>
  );
}
